site_name: My Forgotten Realms
site_description: The Ultimate EET

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Informacje:
      - Nasz bohater: other/leech.md
      - Lista modów: other/mods.md
  - Podróż:
      - Co za dzień: storyline/AR2600-1.md