site_name: My Forgotten Realms
site_description: The Ultimate EET

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/2.3.4/js/dataTables.min.js
  - js/dataTables-init.js

extra_css:
  - https://cdn.datatables.net/2.3.4/css/dataTables.dataTables.min.css
  - css/extra.css

nav:
  - Home: index.md
  - Podróż:
      - Co za dzień!: storyline/AR2600-1.md
  - Informacje:
      - Nasz bohater: other/leech.md
      - Maps: other/maps.md
      - Zadania: other/zadania.md
      - Postaci: other/npc.md
      - Księgozbiór: other/books.md
      - Lista modów: other/mods.md
  